package in.delta.api;
import in.delta.attention.AttentionEngine;import in.delta.checkpoint.CheckpointService;import in.delta.marketdata.*;import in.delta.watchlist.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.MediaType;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin(origins="${delta.cors-origin:http://localhost:3000}") public class DeltaController{
 private final MockMarketDataProvider provider;private final ReliableMarketDataService reliable;private final AttentionEngine engine;private final CheckpointService checkpoints;private final WatchlistService watchlists;private final UserRepository users;
 public DeltaController(MockMarketDataProvider p,ReliableMarketDataService r,AttentionEngine e,CheckpointService c,WatchlistService w,UserRepository u){provider=p;reliable=r;engine=e;checkpoints=c;watchlists=w;users=u;}
 private Long user(){return users.findByEmailIgnoreCase("demo@delta.app").orElseThrow().id;}
 @PostMapping("/auth/login") Object login(@Valid @RequestBody LoginRequest r){var u=watchlists.login(r.email());return Map.of("token","demo-session-"+u.id,"user",Map.of("id",u.id,"email",u.email,"name",u.name));}
 @GetMapping("/watchlists") Object lists(){return watchlists.all(user());}
 @PostMapping("/watchlists") Object create(@Valid @RequestBody NameRequest r){return watchlists.create(user(),r.name());}
 @PatchMapping("/watchlists/{id}") Object rename(@PathVariable Long id,@Valid @RequestBody NameRequest r){return watchlists.rename(id,user(),r.name());}
 @DeleteMapping("/watchlists/{id}") void delete(@PathVariable Long id){watchlists.delete(id,user());}
 @PostMapping("/watchlists/{id}/stocks") Object add(@PathVariable Long id,@Valid @RequestBody InstrumentRequest r){return watchlists.add(id,user(),r.instrumentId().toUpperCase());}
 @DeleteMapping("/watchlists/{id}/stocks/{instrument}") Object remove(@PathVariable Long id,@PathVariable String instrument){return watchlists.remove(id,user(),instrument);}
 @GetMapping("/instruments/search") Object search(@RequestParam(defaultValue="") String q){return provider.searchInstruments(q).stream().map(i->Map.of("instrument",i,"quote",reliable.getQuote(i.id()))).toList();}
 @GetMapping("/instruments/{id}") Object instrument(@PathVariable String id){var i=provider.searchInstruments(id).stream().filter(x->x.id().equalsIgnoreCase(id)).findFirst().orElseThrow();return Map.of("instrument",i,"quote",reliable.getQuote(i.id()),"disclaimer","Verified simulated facts; no recommendation or prediction.");}
 @GetMapping("/watchlists/{id}/attention") Object attention(@PathVariable Long id){var wl=watchlists.all(user()).stream().filter(w->w.id().equals(id)).findFirst().orElseThrow();return wl.instruments().stream().map(this::attentionFor).toList();}
 private Object attentionFor(String symbol){var q=reliable.getQuote(symbol);var cp=checkpoints.get(user(),symbol);double base=cp==null?q.price():cp.price;double ret=base==0?0:(q.price()-base)/base*100;var a=engine.score(new AttentionEngine.Input(ret,Math.max(.8,Math.sqrt(Math.max(1,(System.currentTimeMillis()-(cp==null?q.exchangeTimestamp():cp.capturedAt).toEpochMilli())/86_400_000d))),symbol.equals("TATAMOTORS")?2.1:1.2,symbol.equals("TATAMOTORS")?1.8:1.1,symbol.equals("TATAMOTORS")?-.7:.5,Math.abs(ret)>4));return Map.of("symbol",symbol,"quote",q,"checkpoint",cp==null?Map.of():cp,"returnSinceLastSeen",ret,"attention",a);}
 @PostMapping("/instruments/{id}/acknowledge") Object acknowledge(@PathVariable String id){var q=reliable.getQuote(id);return checkpoints.acknowledge(user(),id,q.price(),q.volume());}
 @PostMapping("/watchlists/{id}/acknowledge-all") Object acknowledgeAll(@PathVariable Long id){var wl=watchlists.all(user()).stream().filter(w->w.id().equals(id)).findFirst().orElseThrow();wl.instruments().forEach(s->{var q=reliable.getQuote(s);checkpoints.acknowledge(user(),s,q.price(),q.volume());});return Map.of("acknowledged",wl.instruments().size());}
 @PostMapping("/dev/scenarios/{scenario}") Object scenario(@PathVariable String scenario){provider.setScenario(scenario.toUpperCase(Locale.ROOT));return Map.of("scenario",provider.scenario());}
 @GetMapping("/system/health") Object health(){long stale=provider.searchInstruments("").stream().map(i->provider.getQuote(i.id())).filter(q->q.qualityStatus()!=MarketDataProvider.QualityStatus.LIVE).count();return Map.of("marketProvider","HEALTHY","database","HEALTHY","redis","OPTIONAL","scenario",provider.scenario(),"staleInstruments",stale);}
 @GetMapping(value="/stream/watchlist/{id}",produces=MediaType.TEXT_EVENT_STREAM_VALUE) SseEmitter stream(@PathVariable Long id){var e=new SseEmitter(30_000L);try{e.send(SseEmitter.event().name("attention").data(attention(id)));e.complete();}catch(Exception x){e.completeWithError(x);}return e;}
 public record LoginRequest(@Email @NotBlank String email){}public record NameRequest(@NotBlank @Size(max=50)String name){}public record InstrumentRequest(@NotBlank String instrumentId){}
}
