'use client';

import {useMemo,useState} from 'react';
import {Activity,AlertTriangle,Bell,Check,ChevronDown,ChevronRight,Clock3,Database,Eye,HeartPulse,Layers3,Menu,Plus,RefreshCw,Search,ShieldCheck,Sparkles,Wifi,X} from 'lucide-react';

type Quality='LIVE'|'DELAYED'|'STALE'|'CONFLICTED';
type Level='NEEDS ATTENTION'|'WORTH WATCHING'|'QUIET';
type Stock={id:string;name:string;symbol:string;price:number;since:number;score:number;level:Level;quality:Quality;updated:string;lastSeen:string;normal:number;volume:number;benchmark:string;benchmarkMove:number;reasons:string[]};

const initial:Stock[]=[
 {id:'tata',name:'Tata Motors',symbol:'TATAMOTORS',price:663.20,since:-6.8,score:83,level:'NEEDS ATTENTION',quality:'LIVE',updated:'14 sec ago',lastSeen:'Mon, 10:32',normal:2.4,volume:2.1,benchmark:'Nifty Auto',benchmarkMove:-0.7,reasons:['2.4× its normal movement','Volume is 2.1× recent average','5.9% weaker than Nifty Auto']},
 {id:'infy',name:'Infosys',symbol:'INFY',price:1481.40,since:4.2,score:67,level:'NEEDS ATTENTION',quality:'LIVE',updated:'11 sec ago',lastSeen:'Tue, 15:08',normal:1.9,volume:1.6,benchmark:'Nifty IT',benchmarkMove:1.1,reasons:['1.9× its normal movement','Volume is 1.6× recent average','Outperformed Nifty IT by 3.1%']},
 {id:'hdfc',name:'HDFC Bank',symbol:'HDFCBANK',price:1694.80,since:-2.6,score:46,level:'WORTH WATCHING',quality:'DELAYED',updated:'15 min delayed',lastSeen:'Yesterday, 12:44',normal:1.3,volume:1.4,benchmark:'Nifty Bank',benchmarkMove:-0.9,reasons:['1.3× its normal movement','Volume is 1.4× recent average','1.7% weaker than Nifty Bank']},
 {id:'reliance',name:'Reliance Industries',symbol:'RELIANCE',price:2954.10,since:1.2,score:34,level:'WORTH WATCHING',quality:'LIVE',updated:'9 sec ago',lastSeen:'Wed, 11:20',normal:.9,volume:1.2,benchmark:'Nifty 50',benchmarkMove:.5,reasons:['Movement is slightly above normal','Volume is 1.2× recent average']},
 {id:'tcs',name:'Tata Consultancy Services',symbol:'TCS',price:3942.60,since:.4,score:18,level:'QUIET',quality:'LIVE',updated:'18 sec ago',lastSeen:'Yesterday, 15:42',normal:.5,volume:.9,benchmark:'Nifty IT',benchmarkMove:.3,reasons:['Movement remains within its usual range']},
 {id:'sbin',name:'State Bank of India',symbol:'SBIN',price:812.30,since:-.7,score:12,level:'QUIET',quality:'LIVE',updated:'16 sec ago',lastSeen:'Tue, 13:10',normal:.6,volume:.8,benchmark:'Nifty Bank',benchmarkMove:-.5,reasons:['No unusual price or volume movement']}
];

const qclass=(q:Quality)=>`quality ${q.toLowerCase()}`;
function Score({value}:{value:number}){const color=value>=60?'#db4b38':value>=30?'#ad6d00':'#1b7b5a';return <span className="score" style={{background:`conic-gradient(${color} ${value*3.6}deg,#e9eeeb 0)`}}><b>{value}</b></span>}

export default function Home(){
 const [stocks,setStocks]=useState(initial),[nav,setNav]=useState<'attention'|'watchlists'|'status'>('attention'),[selected,setSelected]=useState<Stock|null>(null),[quietOpen,setQuietOpen]=useState(false),[mobile,setMobile]=useState(false),[scenario,setScenario]=useState('Stock-specific fall');
 const counts=useMemo(()=>({attention:stocks.filter(s=>s.level==='NEEDS ATTENTION').length,watching:stocks.filter(s=>s.level==='WORTH WATCHING').length,quiet:stocks.filter(s=>s.level==='QUIET').length}),[stocks]);
 const acknowledge=(id:string)=>{setStocks(v=>v.map(s=>s.id===id?{...s,since:0,score:0,level:'QUIET',lastSeen:'Just now',reasons:['Checkpoint updated — no new movement yet']}:s));setSelected(null)};
 const scenarioChange=(v:string)=>{setScenario(v);if(v==='Stale provider')setStocks(initial.map(s=>s.id==='tata'?{...s,quality:'STALE',updated:'Last reliable update 8 min ago'}:s));else if(v==='Conflicting providers')setStocks(initial.map(s=>s.id==='tata'?{...s,quality:'CONFLICTED',updated:'Showing last verified value'}:s));else setStocks(initial)};
 return <div className="shell"><aside className={mobile?'side open':'side'}><div className="brand"><i>Δ</i> DELTA <button onClick={()=>setMobile(false)}><X/></button></div><p>Catch up on what changed.</p><nav><button className={nav==='attention'?'active':''} onClick={()=>{setNav('attention');setMobile(false)}}><Bell/>Attention <b>{counts.attention+counts.watching}</b></button><button className={nav==='watchlists'?'active':''} onClick={()=>{setNav('watchlists');setMobile(false)}}><Layers3/>Watchlists</button><button className={nav==='status'?'active':''} onClick={()=>{setNav('status');setMobile(false)}}><HeartPulse/>Data status</button></nav><section className="lists"><label>WATCHLISTS <Plus/></label><button className="chosen">● Core holdings <small>{stocks.length}</small></button><button>● Banks <small>4</small></button><button>● Tech <small>3</small></button></section><section className="scenario"><label><Sparkles/> DEMO SCENARIO</label><select value={scenario} onChange={e=>scenarioChange(e.target.value)}><option>Stock-specific fall</option><option>Normal market</option><option>Stale provider</option><option>Conflicting providers</option></select><small>Simulated market data</small></section><div className="user"><i>SK</i><span><b>Saumiya</b><small>Demo investor</small></span></div></aside>
 <main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><span className="market"><i/> <b>MARKET OPEN</b><small>NSE · Closes 3:30 PM</small></span><span className="actions"><Search/><RefreshCw/><b>SIMULATED DATA</b></span></header>
 {nav==='attention'?<Attention stocks={stocks} counts={counts} open={setSelected} acknowledge={acknowledge} quietOpen={quietOpen} setQuietOpen={setQuietOpen}/>:nav==='watchlists'?<Watchlists stocks={stocks} open={setSelected}/>:<Status stocks={stocks}/>}</main>
 {selected&&<Detail stock={selected} close={()=>setSelected(null)} acknowledge={()=>acknowledge(selected.id)}/>}</div>
}

function Intro({children,action}:{children:React.ReactNode;action?:React.ReactNode}){return <section className="intro"><div>{children}</div>{action}</section>}
function Attention({stocks,counts,open,acknowledge,quietOpen,setQuietOpen}:{stocks:Stock[];counts:{attention:number;watching:number;quiet:number};open:(s:Stock)=>void;acknowledge:(id:string)=>void;quietOpen:boolean;setQuietOpen:(v:boolean)=>void}){const active=stocks.filter(s=>s.level!=='QUIET').sort((a,b)=>b.score-a.score),quiet=stocks.filter(s=>s.level==='QUIET');return <div className="content"><Intro action={<button className="outline" onClick={()=>active.forEach(s=>acknowledge(s.id))}><Check/>Mark all reviewed</button>}><em>FRIDAY, 4 SEPTEMBER</em><h1>Welcome back, Saumiya.</h1><p>You were away for <b>3 days.</b> Here’s the signal without the noise.</p></Intro><section className="summary"><Metric n={counts.attention} label="Need attention" sub="Meaningful change" kind="red"/><Metric n={counts.watching} label="Worth watching" sub="Notable, not urgent" kind="amber"/><Metric n={counts.quiet} label="Stayed quiet" sub="Nothing unusual" kind="green"/><div className="filtered"><ShieldCheck/><span><b>Only {counts.attention+counts.watching} of {stocks.length} surfaced</b><small>Delta filters ordinary movement.</small></span></div></section><div className="section-head"><span><i/> <b>Your attention inbox</b> <small>{active.length}</small></span><p>Ranked by meaningful change since your last check</p></div><div className="cards">{active.map(s=><Card key={s.id} s={s} open={()=>open(s)} acknowledge={()=>acknowledge(s.id)}/>)}</div><button className="quiet-toggle" onClick={()=>setQuietOpen(!quietOpen)}><span><Check/><i><b>{quiet.length} stocks stayed quiet</b><small>No movement outside their normal range</small></i></span><ChevronDown className={quietOpen?'up':''}/></button>{quietOpen&&<div className="quiet-list">{quiet.map(s=><button key={s.id} onClick={()=>open(s)}><span><b>{s.name}</b><small>{s.symbol}</small></span><strong>₹{s.price.toLocaleString('en-IN')}</strong><em>{s.since}%</em><i>QUIET · {s.score}</i></button>)}</div>}<footer><ShieldCheck/>Delta explains market movement. It does not provide investment advice.</footer></div>}
function Metric({n,label,sub,kind}:{n:number;label:string;sub:string;kind:string}){return <div className="metric"><strong className={kind}>{n}</strong><span><b>{label}</b><small>{sub}</small></span></div>}
function Card({s,open,acknowledge}:{s:Stock;open:()=>void;acknowledge:()=>void}){return <article className="card"><div className="card-top"><Company s={s}/><span className="level"><i className={s.score>=60?'red':'amber'}>{s.level}</i><Score value={s.score}/></span></div><div className="price"><span><b>₹{s.price.toLocaleString('en-IN',{minimumFractionDigits:2})}</b><em className={s.since<0?'down':'up'}>{s.since>0?'+':''}{s.since}% <small>since you last checked</small></em></span><Activity/></div><section className="reasons"><label>WHY IT MATTERS</label>{s.reasons.map((r,i)=><div key={r}><i>{i+1}</i><span>{r}</span><b>+{i===0?31:i===1?18:14}</b></div>)}</section>{(s.quality==='STALE'||s.quality==='CONFLICTED')&&<div className="warning"><AlertTriangle/>{s.quality==='STALE'?'Provider unavailable. Showing the last reliable quote.':'Providers disagree. Showing the last verified value.'}</div>}<div className="card-foot"><span><i className={qclass(s.quality)}>{s.quality}</i><small>{s.updated}</small><small>Last checked {s.lastSeen}</small></span><span><button onClick={acknowledge}><Eye/>Mark seen</button><button className="story-btn" onClick={open}>View change story<ChevronRight/></button></span></div></article>}
function Company({s}:{s:Stock}){return <span className="company"><i>{s.symbol.slice(0,2)}</i><span><b>{s.name}</b><small>{s.symbol} · NSE</small></span></span>}

function Detail({stock:s,close,acknowledge}:{stock:Stock;close:()=>void;acknowledge:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="detail"><button className="close" onClick={close}><X/></button><div className="detail-head"><Company s={s}/><Score value={s.score}/></div><div className="detail-price"><span><small>CURRENT PRICE</small><b>₹{s.price.toLocaleString('en-IN',{minimumFractionDigits:2})}</b></span><span><small>SINCE LAST SEEN</small><b className={s.since<0?'down':'up'}>{s.since>0?'+':''}{s.since}%</b></span><i className={qclass(s.quality)}>{s.quality}</i></div><section className="story"><label>THE CHANGE STORY</label><h2>{s.name} has {s.since<0?'fallen':'risen'} {Math.abs(s.since)}% since you last checked.</h2><p>The move is <b>{s.normal}× larger</b> than its typical movement over the same duration. Trading volume is <b>{s.volume}× normal</b>, while {s.benchmark} is {s.benchmarkMove<0?'down':'up'} only {Math.abs(s.benchmarkMove)}%.</p></section><section className="timeline"><label>CHANGE TIMELINE</label><Timeline time={s.lastSeen} title="You last checked" value="Your knowledge checkpoint"/><Timeline time="Tuesday, 14:21" title="Unusual trading volume detected" value={`${s.volume}× recent average`}/><Timeline time="Today, 15:30" title="Meaningful price movement detected" value={`Current price ₹${s.price.toFixed(2)}`}/></section><button className="ack" onClick={acknowledge}><Eye/>I’ve seen this — update my checkpoint</button><p className="note">Auto-refresh never changes what you know. Only acknowledgement resets the baseline.</p></section></div>}
function Timeline({time,title,value}:{time:string;title:string;value:string}){return <div><i/><span><small>{time}</small><b>{title}</b><em>{value}</em></span></div>}
function Watchlists({stocks,open}:{stocks:Stock[];open:(s:Stock)=>void}){return <div className="content"><Intro action={<button className="outline"><Plus/>Add stock</button>}><em>YOUR COLLECTIONS</em><h1>Core holdings</h1><p>{stocks.length} stocks · each with its own knowledge checkpoint</p></Intro><div className="table"><div><b>Instrument</b><b>Price</b><b>Since seen</b><b>Attention</b><b>Freshness</b></div>{stocks.map(s=><button key={s.id} onClick={()=>open(s)}><Company s={s}/><span>₹{s.price.toLocaleString('en-IN')}</span><span className={s.since<0?'down':'up'}>{s.since}%</span><span>{s.level} · {s.score}</span><i className={qclass(s.quality)}>{s.quality}</i></button>)}</div></div>}
function Status({stocks}:{stocks:Stock[]}){const bad=stocks.filter(s=>s.quality==='STALE'||s.quality==='CONFLICTED').length;return <div className="content"><Intro action={<span className="healthy"><Wifi/>{bad?'DEGRADED':'ALL SYSTEMS HEALTHY'}</span>}><em>SYSTEM HEALTH</em><h1>Data you can trust.</h1><p>Freshness and degraded states are shown, never hidden.</p></Intro><div className="status-grid"><Health icon={<Activity/>} label="Market feed" value={bad?'Degraded':'Healthy'} note="Last successful ingestion 7 sec ago"/><Health icon={<Database/>} label="PostgreSQL" value="Healthy" note="Primary store · 18 ms"/><Health icon={<Layers3/>} label="Redis cache" value="Healthy" note="Optional cache · 3 ms"/><Health icon={<Clock3/>} label="Stale instruments" value={String(bad)} note={bad?'Last-known-good values in use':'All quotes within threshold'}/></div><section className="guide"><h2>Quality status guide</h2>{(['LIVE','DELAYED','STALE','CONFLICTED'] as Quality[]).map(q=><div key={q}><i className={qclass(q)}>{q}</i><span><b>{q==='LIVE'?'Fresh exchange timestamp':q==='DELAYED'?'Provider-declared delay':q==='STALE'?'Last-known-good value':'Providers disagree'}</b><small>{q==='CONFLICTED'?'No silent provider selection':'The UI states exactly how current this value is'}</small></span></div>)}</section></div>}
function Health({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <section className="health">{icon}<small>{label}</small><b>{value}</b><p>{note}</p></section>}
